name: Create release

on:
  push:
    branches:
      - "main"


jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: rlespinasse/shortify-git-revision@v1
      with:
        name: GITHUB_SHA

    - name: Zip Folders
      run: |
          zip -r IC-7.simhubdash IC-7/
          zip -r ADU5.simhubdash ADU5/

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "${{ GITHUB_SHA_SHORT }}"
        title: "Latest Build"
        files: |
          *.simhubdash
