name: Create release

on:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Zip Folders
      run: |
           cd IC-7 && zip -r IC-7.simhubdash . && cd .. 
           cd ADU5 && zip -r ADU5.simhubdash . && cd .. 

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development Build"
        files: |
          */*.simhubdash
